name: absensi_alma
description: "Aplikasi Absensi Karyawan PT Alma "
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.0.0
  reactive_button: ^0.0.9
  cupertino_icons:
  flutter_bloc:
  dio:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/static/Inter_18pt-Light.ttf
        - asset: assets/fonts/Inter/static/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/static/Inter_18pt-Italic.ttf
          style: italic
